CREATE TABLE IF NOT EXISTS orders (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id          TEXT,
  asset           TEXT,
  side            TEXT,
  side_id         TEXT,
  action          TEXT,
  algorithm_id    INTEGER,
  algorithm       TEXT,
  type            TEXT,
  pair            TEXT,
  quantity        REAL,
  price           REAL,
  amount          REAL,
  net_market_amount REAL,
  filled          REAL,
  vwap            REAL,
  filled_amount   REAL,
  fees            REAL,
  net_proceeds    REAL,
  status          TEXT,
  status_code     TEXT,
  routing_option  TEXT,
  routing_type    TEXT,
  time_in_force   TEXT,
  expires         TEXT,
  dateupdated     TEXT,
  date_added      TEXT,
  client_order_id TEXT,
  user_tx_id      TEXT,
  o_action        TEXT,
  algo_id         INTEGER,
  destination     TEXT,
  error           TEXT,
  response_json   TEXT,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
